spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bugpilot

server:
  port: 8080

logging:
  level:
    root: INFO
    com.techio.bugpilot: DEBUG
    org.springframework.security: DEBUG
